run:
  skip-files:
    - ".*_mock.go"
    - ".*.pb.go"
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - gosec
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - golint
    - interfacer
    - unconvert
    - goconst
    - unparam
    - nakedret
    - scopelint
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/insolar/observer-framework

issues:
  exclude-rules:
    - text: "S1021:"
      linters:
        - gosimple
