name: tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 * * *
  pull_request:
  workflow_dispatch:
    inputs:
      TestCount:
        description: 'The go test count'
        required: false
        default: '1000'
      TestTimeout:
        description: 'The go test timeout'
        required: false
        default: '240m'

env:
  GO_VERSION: 1.14
  CI_GOMAXPROCS: 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make all
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/observer-framework/observer-framework/go
    steps:
      - name: set pull_request run params
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        run: |
          echo "TEST_COUNT=10" >> $GITHUB_ENV
      - name: set scheduled run params
        if: github.event_name == 'schedule'
        run: |
          echo "TEST_COUNT=1000" >> $GITHUB_ENV
          echo "TEST_ARGS=-timeout 240m" >> $GITHUB_ENV
      - name: set dispatch run params
        if: github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
        run: |
          echo "TEST_COUNT=${{ github.event.inputs.TestCount }}" >> $GITHUB_ENV
          echo "TEST_ARGS=-timeout ${{ github.event.inputs.TestTimeout }}" >> $GITHUB_ENV
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/observer-framework
          fetch-depth: 1
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make mod unit
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/observer-framework
      - name: Send failure notification to Slack
        if: failure() && github.event_name == 'schedule'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTIONS_NOTIFICATIONS_SLACK_HOOK_URL }}
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/observer-framework/observer-framework/go
    steps:
      - name: set pull_request run params
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        run: |
          echo "TEST_COUNT=10" >> $GITHUB_ENV
      - name: set scheduled run params
        if: github.event_name == 'schedule'
        run: |
          echo "TEST_COUNT=1000" >> $GITHUB_ENV
          echo "TEST_ARGS=-timeout 240m" >> $GITHUB_ENV
      - name: set dispatch run params
        if: github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
        run: |
          echo "TEST_COUNT=${{ github.event.inputs.TestCount }}" >> $GITHUB_ENV
          echo "TEST_ARGS=-timeout ${{ github.event.inputs.TestTimeout }}" >> $GITHUB_ENV
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/observer-framework
          fetch-depth: 1
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make mod integration
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/observer-framework
      - name: Send failure notification to Slack
        if: failure() && github.event_name == 'schedule'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTIONS_NOTIFICATIONS_SLACK_HOOK_URL }}
  test-with-coverage:
    name: tests with coverage
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/observer-framework/observer-framework/go
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/observer-framework
          fetch-depth: 1
      - name: Add bin to path
        run: echo "${{env.GOPATH}}/bin" >> $GITHUB_PATH
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make go-acc all test-with-coverage
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/observer-framework
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -f coverage.out -y .codecov.yml -n coverage-report
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/observer-framework
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/observer-framework/observer-framework/go
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/observer-framework
          fetch-depth: 1
      - name: Add bin to path
        run: echo "${{env.GOPATH}}/bin" >> $GITHUB_PATH
      - name: Install golangci
        run: make all golangci
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/observer-framework
      - name: Run golangci-lint
        run: make lint
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/observer-framework
